/* Generated by Pyrex 0.9.8.5 on Wed Feb 10 01:29:19 2010 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)	PyInt_AsLong(o)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#include "limits.h"


typedef struct {PyObject **p; int i; char *s; long n;} __Pyx_StringTabEntry; /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char **__pyx_f;

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static void __Pyx_AddTraceback(char *funcname); /*proto*/

/* Declarations from shibazuke */


/* Declarations from implementation of shibazuke */

enum  {
  __pyx_e_9shibazuke_INT = 0x00,
  __pyx_e_9shibazuke_LONG = 0x10,
  __pyx_e_9shibazuke_FLOAT = 0x20,
  __pyx_e_9shibazuke_STR = 0x30,
  __pyx_e_9shibazuke_USTR = 0x40,
  __pyx_e_9shibazuke_TUPLE = 0x50,
  __pyx_e_9shibazuke_LIST = 0x60,
  __pyx_e_9shibazuke_DICT = 0x70,
  __pyx_e_9shibazuke_REFS = 0xE0,
  __pyx_e_9shibazuke_SPECIALS = 0xF0
};

struct __pyx_obj_9shibazuke_Serializer {
  PyObject_HEAD
  struct __pyx_vtabstruct_9shibazuke_Serializer *__pyx_vtab;
  PyDictObject *_nummap;
  PyDictObject *_strmap;
  PyListObject *_objs;
  PyDictObject *_buildings;
};


struct __pyx_vtabstruct_9shibazuke_Serializer {
  PyObject *(*_build_ref)(struct __pyx_obj_9shibazuke_Serializer *,int);
  PyObject *(*_handle_string)(struct __pyx_obj_9shibazuke_Serializer *,PyObject *);
  PyObject *(*_build)(struct __pyx_obj_9shibazuke_Serializer *,PyObject *);
};
static struct __pyx_vtabstruct_9shibazuke_Serializer *__pyx_vtabptr_9shibazuke_Serializer;

static PyTypeObject *__pyx_ptype_9shibazuke_Serializer = 0;

static char __pyx_k1[] = "_ustrmap";
static char __pyx_k2[] = "_build_big_int";
static char __pyx_k3[] = "_build_num";
static char __pyx_k4[] = "Too many object";
static char __pyx_k5[] = "get";
static char __pyx_k6[] = "_build_str";
static char __pyx_k7[] = "Unsupported type";
static char __pyx_k8[] = "sz\x00\x00\x01";
static char __pyx_k9[] = "";
static char __pyx_k10[] = "join";
static char __pyx_k11[] = "struct";
static char __pyx_k12[] = "sys";

static PyObject *__pyx_n__build_big_int;
static PyObject *__pyx_n__build_num;
static PyObject *__pyx_n__build_str;
static PyObject *__pyx_n__ustrmap;
static PyObject *__pyx_n_get;
static PyObject *__pyx_n_join;
static PyObject *__pyx_n_struct;
static PyObject *__pyx_n_sys;

static PyObject *__pyx_k4p;
static PyObject *__pyx_k7p;
static PyObject *__pyx_k8p;
static PyObject *__pyx_k9p;

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_n__build_big_int, 1, __pyx_k2, sizeof(__pyx_k2)},
  {&__pyx_n__build_num, 1, __pyx_k3, sizeof(__pyx_k3)},
  {&__pyx_n__build_str, 1, __pyx_k6, sizeof(__pyx_k6)},
  {&__pyx_n__ustrmap, 1, __pyx_k1, sizeof(__pyx_k1)},
  {&__pyx_n_get, 1, __pyx_k5, sizeof(__pyx_k5)},
  {&__pyx_n_join, 1, __pyx_k10, sizeof(__pyx_k10)},
  {&__pyx_n_struct, 1, __pyx_k11, sizeof(__pyx_k11)},
  {&__pyx_n_sys, 1, __pyx_k12, sizeof(__pyx_k12)},
  {&__pyx_k4p, 0, __pyx_k4, sizeof(__pyx_k4)},
  {&__pyx_k7p, 0, __pyx_k7, sizeof(__pyx_k7)},
  {&__pyx_k8p, 0, __pyx_k8, sizeof(__pyx_k8)},
  {&__pyx_k9p, 0, __pyx_k9, sizeof(__pyx_k9)},
  {0, 0, 0, 0}
};



/* Implementation of shibazuke */

static int __pyx_f_9shibazuke_10Serializer___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_9shibazuke_10Serializer___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  static char *__pyx_argnames[] = {0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "", __pyx_argnames)) return -1;
  Py_INCREF(__pyx_v_self);

  /* "c:\src\shibazuke\shibazuke.pyx":77 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  if (!__Pyx_TypeTest(__pyx_1, (&PyDict_Type))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 77; goto __pyx_L1;}
  Py_DECREF(((PyObject *)((struct __pyx_obj_9shibazuke_Serializer *)__pyx_v_self)->_nummap));
  ((struct __pyx_obj_9shibazuke_Serializer *)__pyx_v_self)->_nummap = ((PyDictObject *)__pyx_1);
  __pyx_1 = 0;

  /* "c:\src\shibazuke\shibazuke.pyx":78 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
  if (!__Pyx_TypeTest(__pyx_1, (&PyDict_Type))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 78; goto __pyx_L1;}
  Py_DECREF(((PyObject *)((struct __pyx_obj_9shibazuke_Serializer *)__pyx_v_self)->_strmap));
  ((struct __pyx_obj_9shibazuke_Serializer *)__pyx_v_self)->_strmap = ((PyDictObject *)__pyx_1);
  __pyx_1 = 0;

  /* "c:\src\shibazuke\shibazuke.pyx":79 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_v_self, __pyx_n__ustrmap, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\shibazuke\shibazuke.pyx":80 */
  __pyx_1 = PyList_New(0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  if (!__Pyx_TypeTest(__pyx_1, (&PyList_Type))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; goto __pyx_L1;}
  Py_DECREF(((PyObject *)((struct __pyx_obj_9shibazuke_Serializer *)__pyx_v_self)->_objs));
  ((struct __pyx_obj_9shibazuke_Serializer *)__pyx_v_self)->_objs = ((PyListObject *)__pyx_1);
  __pyx_1 = 0;

  /* "c:\src\shibazuke\shibazuke.pyx":81 */
  __pyx_1 = PyDict_New(); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  if (!__Pyx_TypeTest(__pyx_1, (&PyDict_Type))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; goto __pyx_L1;}
  Py_DECREF(((PyObject *)((struct __pyx_obj_9shibazuke_Serializer *)__pyx_v_self)->_buildings));
  ((struct __pyx_obj_9shibazuke_Serializer *)__pyx_v_self)->_buildings = ((PyDictObject *)__pyx_1);
  __pyx_1 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("shibazuke.Serializer.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_9shibazuke_10Serializer__build_num(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9shibazuke_10Serializer__build_num(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_flag;
  long __pyx_v_num;
  char __pyx_v_c[6];
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  static char *__pyx_argnames[] = {"flag","num",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "il", __pyx_argnames, &__pyx_v_flag, &__pyx_v_num)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "c:\src\shibazuke\shibazuke.pyx":86 */
  __pyx_1 = 0 <= __pyx_v_num;
  if (__pyx_1) {
    __pyx_1 = __pyx_v_num <= 12;
  }
  if (__pyx_1) {

    /* "c:\src\shibazuke\shibazuke.pyx":87 */
    (__pyx_v_c[0]) = ((char)(__pyx_v_flag | __pyx_v_num));

    /* "c:\src\shibazuke\shibazuke.pyx":88 */
    (__pyx_v_c[1]) = 0;
    goto __pyx_L2;
  }
  __pyx_1 = (-128) <= __pyx_v_num;
  if (__pyx_1) {
    __pyx_1 = __pyx_v_num <= 127;
  }
  if (__pyx_1) {

    /* "c:\src\shibazuke\shibazuke.pyx":90 */
    (__pyx_v_c[0]) = ((char)(__pyx_v_flag + 13));

    /* "c:\src\shibazuke\shibazuke.pyx":91 */
    (__pyx_v_c[1]) = ((char)__pyx_v_num);

    /* "c:\src\shibazuke\shibazuke.pyx":92 */
    (__pyx_v_c[2]) = 0;
    goto __pyx_L2;
  }
  __pyx_1 = (-32768) <= __pyx_v_num;
  if (__pyx_1) {
    __pyx_1 = __pyx_v_num <= 32767;
  }
  if (__pyx_1) {

    /* "c:\src\shibazuke\shibazuke.pyx":94 */
    (__pyx_v_c[0]) = ((char)(__pyx_v_flag + 14));

    /* "c:\src\shibazuke\shibazuke.pyx":95 */
    (__pyx_v_c[1]) = ((char)(__pyx_v_num & 0xff));

    /* "c:\src\shibazuke\shibazuke.pyx":96 */
    (__pyx_v_c[2]) = ((char)((__pyx_v_num >> 8) & 0xff));

    /* "c:\src\shibazuke\shibazuke.pyx":97 */
    (__pyx_v_c[3]) = 0;
    goto __pyx_L2;
  }
  __pyx_1 = (((-2147483647) - 1) <= __pyx_v_num);
  if (__pyx_1) {
    __pyx_1 = (__pyx_v_num <= 2147483647);
  }
  if (__pyx_1) {

    /* "c:\src\shibazuke\shibazuke.pyx":99 */
    (__pyx_v_c[0]) = ((char)(__pyx_v_flag + 15));

    /* "c:\src\shibazuke\shibazuke.pyx":100 */
    (__pyx_v_c[1]) = ((char)(__pyx_v_num & 0xff));

    /* "c:\src\shibazuke\shibazuke.pyx":101 */
    (__pyx_v_c[2]) = ((char)((__pyx_v_num >> 8) & 0xff));

    /* "c:\src\shibazuke\shibazuke.pyx":102 */
    (__pyx_v_c[3]) = ((char)((__pyx_v_num >> 16) & 0xff));

    /* "c:\src\shibazuke\shibazuke.pyx":103 */
    (__pyx_v_c[4]) = ((char)((__pyx_v_num >> 24) & 0xff));

    /* "c:\src\shibazuke\shibazuke.pyx":104 */
    (__pyx_v_c[5]) = 0;
    goto __pyx_L2;
  }
  /*else*/ {
    __pyx_2 = PyObject_GetAttr(__pyx_v_self, __pyx_n__build_big_int); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(__pyx_v_flag); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
    __pyx_4 = PyInt_FromLong(__pyx_v_num); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
    __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_3);
    PyTuple_SET_ITEM(__pyx_5, 1, __pyx_4);
    __pyx_3 = 0;
    __pyx_4 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_5); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_r = __pyx_3;
    __pyx_3 = 0;
    goto __pyx_L0;
  }
  __pyx_L2:;

  /* "c:\src\shibazuke\shibazuke.pyx":107 */
  __pyx_4 = PyString_FromString(__pyx_v_c); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; goto __pyx_L1;}
  __pyx_r = __pyx_4;
  __pyx_4 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("shibazuke.Serializer._build_num");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_9shibazuke_10Serializer__build_ref(struct __pyx_obj_9shibazuke_Serializer *__pyx_v_self,int __pyx_v_n) {
  PyObject *__pyx_v_s;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  int __pyx_5;
  int __pyx_6;
  Py_INCREF(__pyx_v_self);
  __pyx_v_s = Py_None; Py_INCREF(Py_None);

  /* "c:\src\shibazuke\shibazuke.pyx":110 */
  __pyx_1 = PyObject_GetAttr(((PyObject *)__pyx_v_self), __pyx_n__build_num); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(__pyx_e_9shibazuke_REFS); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_n); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_v_s);
  __pyx_v_s = __pyx_2;
  __pyx_2 = 0;

  /* "c:\src\shibazuke\shibazuke.pyx":111 */
  __pyx_5 = PyObject_IsTrue(__pyx_v_s); if (__pyx_5 < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; goto __pyx_L1;}
  __pyx_6 = (!__pyx_5);
  if (__pyx_6) {
    __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    Py_INCREF(__pyx_k4p);
    PyTuple_SET_ITEM(__pyx_3, 0, __pyx_k4p);
    __pyx_1 = PyObject_CallObject(PyExc_ValueError, __pyx_3); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __Pyx_Raise(__pyx_1, 0, 0);
    Py_DECREF(__pyx_1); __pyx_1 = 0;
    {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "c:\src\shibazuke\shibazuke.pyx":113 */
  Py_INCREF(__pyx_v_s);
  __pyx_r = __pyx_v_s;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("shibazuke.Serializer._build_ref");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_s);
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_f_9shibazuke_10Serializer__handle_string(struct __pyx_obj_9shibazuke_Serializer *__pyx_v_self,PyObject *__pyx_v_s) {
  PyObject *__pyx_v_n;
  PyObject *__pyx_v_e;
  PyObject *__pyx_v_pos;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  Py_ssize_t __pyx_5;
  int __pyx_6;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_s);
  __pyx_v_n = Py_None; Py_INCREF(Py_None);
  __pyx_v_e = Py_None; Py_INCREF(Py_None);
  __pyx_v_pos = Py_None; Py_INCREF(Py_None);

  /* "c:\src\shibazuke\shibazuke.pyx":117 */
  __pyx_1 = PyObject_GetAttr(((PyObject *)__pyx_v_self->_strmap), __pyx_n_get); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  Py_INCREF(__pyx_v_s);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_s);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 117; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_v_n);
  __pyx_v_n = __pyx_3;
  __pyx_3 = 0;

  /* "c:\src\shibazuke\shibazuke.pyx":118 */
  __pyx_4 = __pyx_v_n != Py_None;
  if (__pyx_4) {
    __pyx_4 = PyInt_AsLong(__pyx_v_n); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
    __pyx_1 = ((struct __pyx_vtabstruct_9shibazuke_Serializer *)__pyx_v_self->__pyx_vtab)->_build_ref(__pyx_v_self,__pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 119; goto __pyx_L1;}
    __pyx_r = __pyx_1;
    __pyx_1 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "c:\src\shibazuke\shibazuke.pyx":121 */
  __pyx_2 = PyObject_GetAttr(((PyObject *)__pyx_v_self), __pyx_n__build_str); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_e_9shibazuke_STR); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
  __pyx_1 = PyTuple_New(2); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_3);
  Py_INCREF(__pyx_v_s);
  PyTuple_SET_ITEM(__pyx_1, 1, __pyx_v_s);
  __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_v_e);
  __pyx_v_e = __pyx_3;
  __pyx_3 = 0;

  /* "c:\src\shibazuke\shibazuke.pyx":122 */
  __pyx_5 = PyObject_Length(__pyx_v_e); if (__pyx_5 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 122; goto __pyx_L1;}
  __pyx_4 = (__pyx_5 <= 4);
  if (__pyx_4) {
    Py_INCREF(__pyx_v_e);
    __pyx_r = __pyx_v_e;
    goto __pyx_L0;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "c:\src\shibazuke\shibazuke.pyx":125 */
  __pyx_5 = PyObject_Length(((PyObject *)__pyx_v_self->_objs)); if (__pyx_5 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  __pyx_2 = PyInt_FromSsize_t(__pyx_5); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; goto __pyx_L1;}
  Py_DECREF(__pyx_v_pos);
  __pyx_v_pos = __pyx_2;
  __pyx_2 = 0;

  /* "c:\src\shibazuke\shibazuke.pyx":126 */
  __pyx_6 = PyList_Append(((PyObject *)__pyx_v_self->_objs),__pyx_v_e); if (__pyx_6 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; goto __pyx_L1;}

  /* "c:\src\shibazuke\shibazuke.pyx":127 */
  if (PyObject_SetItem(((PyObject *)__pyx_v_self->_strmap), __pyx_v_s, __pyx_v_pos) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 127; goto __pyx_L1;}

  /* "c:\src\shibazuke\shibazuke.pyx":129 */
  __pyx_4 = PyInt_AsLong(__pyx_v_pos); if (PyErr_Occurred()) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
  __pyx_1 = ((struct __pyx_vtabstruct_9shibazuke_Serializer *)__pyx_v_self->__pyx_vtab)->_build_ref(__pyx_v_self,__pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 129; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("shibazuke.Serializer._handle_string");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_n);
  Py_DECREF(__pyx_v_e);
  Py_DECREF(__pyx_v_pos);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_s);
  return __pyx_r;
}

static PyObject *__pyx_f_9shibazuke_10Serializer__build(struct __pyx_obj_9shibazuke_Serializer *__pyx_v_self,PyObject *__pyx_v_obj) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_obj);

  /* "c:\src\shibazuke\shibazuke.pyx":132 */
  __pyx_1 = PyString_CheckExact(__pyx_v_obj);
  if (__pyx_1) {
    __pyx_2 = ((struct __pyx_vtabstruct_9shibazuke_Serializer *)__pyx_v_self->__pyx_vtab)->_handle_string(__pyx_v_self,__pyx_v_obj); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; goto __pyx_L1;}
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L0;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "c:\src\shibazuke\shibazuke.pyx":135 */
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  Py_INCREF(__pyx_k7p);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_k7p);
  __pyx_3 = PyObject_CallObject(PyExc_ValueError, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __Pyx_Raise(__pyx_3, 0, 0);
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("shibazuke.Serializer._build");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_obj);
  return __pyx_r;
}

static PyObject *__pyx_f_9shibazuke_10Serializer_dumps(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_9shibazuke_10Serializer_dumps(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_obj = 0;
  PyObject *__pyx_v_s;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"obj",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_obj)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_obj);
  __pyx_v_s = Py_None; Py_INCREF(Py_None);

  /* "c:\src\shibazuke\shibazuke.pyx":138 */
  __pyx_1 = ((struct __pyx_vtabstruct_9shibazuke_Serializer *)((struct __pyx_obj_9shibazuke_Serializer *)__pyx_v_self)->__pyx_vtab)->_build(((struct __pyx_obj_9shibazuke_Serializer *)__pyx_v_self),__pyx_v_obj); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 138; goto __pyx_L1;}
  Py_DECREF(__pyx_v_s);
  __pyx_v_s = __pyx_1;
  __pyx_1 = 0;

  /* "c:\src\shibazuke\shibazuke.pyx":139 */
  __pyx_2 = PyList_Append(((PyObject *)((struct __pyx_obj_9shibazuke_Serializer *)__pyx_v_self)->_objs),__pyx_v_s); if (__pyx_2 == -1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 139; goto __pyx_L1;}

  /* "c:\src\shibazuke\shibazuke.pyx":140 */
  __pyx_1 = PyObject_GetAttr(__pyx_k9p, __pyx_n_join); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  Py_INCREF(((PyObject *)((struct __pyx_obj_9shibazuke_Serializer *)__pyx_v_self)->_objs));
  PyTuple_SET_ITEM(__pyx_3, 0, ((PyObject *)((struct __pyx_obj_9shibazuke_Serializer *)__pyx_v_self)->_objs));
  __pyx_4 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_1 = PyNumber_Add(__pyx_k8p, __pyx_4); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 140; goto __pyx_L1;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("shibazuke.Serializer.dumps");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_s);
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_obj);
  return __pyx_r;
}
static struct __pyx_vtabstruct_9shibazuke_Serializer __pyx_vtable_9shibazuke_Serializer;

static PyObject *__pyx_tp_new_9shibazuke_Serializer(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_9shibazuke_Serializer *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_9shibazuke_Serializer *)o);
  *(struct __pyx_vtabstruct_9shibazuke_Serializer **)&p->__pyx_vtab = __pyx_vtabptr_9shibazuke_Serializer;
  p->_nummap = ((PyDictObject *)Py_None); Py_INCREF(Py_None);
  p->_strmap = ((PyDictObject *)Py_None); Py_INCREF(Py_None);
  p->_objs = ((PyListObject *)Py_None); Py_INCREF(Py_None);
  p->_buildings = ((PyDictObject *)Py_None); Py_INCREF(Py_None);
  return o;
}

static void __pyx_tp_dealloc_9shibazuke_Serializer(PyObject *o) {
  struct __pyx_obj_9shibazuke_Serializer *p = (struct __pyx_obj_9shibazuke_Serializer *)o;
  Py_XDECREF(((PyObject *)p->_nummap));
  Py_XDECREF(((PyObject *)p->_strmap));
  Py_XDECREF(((PyObject *)p->_objs));
  Py_XDECREF(((PyObject *)p->_buildings));
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_9shibazuke_Serializer(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_9shibazuke_Serializer *p = (struct __pyx_obj_9shibazuke_Serializer *)o;
  if (p->_nummap) {
    e = (*v)(((PyObject*)p->_nummap), a); if (e) return e;
  }
  if (p->_strmap) {
    e = (*v)(((PyObject*)p->_strmap), a); if (e) return e;
  }
  if (p->_objs) {
    e = (*v)(((PyObject*)p->_objs), a); if (e) return e;
  }
  if (p->_buildings) {
    e = (*v)(((PyObject*)p->_buildings), a); if (e) return e;
  }
  return 0;
}

static int __pyx_tp_clear_9shibazuke_Serializer(PyObject *o) {
  struct __pyx_obj_9shibazuke_Serializer *p = (struct __pyx_obj_9shibazuke_Serializer *)o;
  PyObject *t;
  t = ((PyObject *)p->_nummap); 
  p->_nummap = ((PyDictObject *)Py_None); Py_INCREF(Py_None);
  Py_XDECREF(t);
  t = ((PyObject *)p->_strmap); 
  p->_strmap = ((PyDictObject *)Py_None); Py_INCREF(Py_None);
  Py_XDECREF(t);
  t = ((PyObject *)p->_objs); 
  p->_objs = ((PyListObject *)Py_None); Py_INCREF(Py_None);
  Py_XDECREF(t);
  t = ((PyObject *)p->_buildings); 
  p->_buildings = ((PyDictObject *)Py_None); Py_INCREF(Py_None);
  Py_XDECREF(t);
  return 0;
}

static struct PyMethodDef __pyx_methods_9shibazuke_Serializer[] = {
  {"_build_num", (PyCFunction)__pyx_f_9shibazuke_10Serializer__build_num, METH_VARARGS|METH_KEYWORDS, 0},
  {"dumps", (PyCFunction)__pyx_f_9shibazuke_10Serializer_dumps, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Serializer = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_Serializer = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Serializer = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Serializer = {
  0, /*bf_getreadbuffer*/
  0, /*bf_getwritebuffer*/
  0, /*bf_getsegcount*/
  0, /*bf_getcharbuffer*/
};

PyTypeObject __pyx_type_9shibazuke_Serializer = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "shibazuke.Serializer", /*tp_name*/
  sizeof(struct __pyx_obj_9shibazuke_Serializer), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_9shibazuke_Serializer, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_Serializer, /*tp_as_number*/
  &__pyx_tp_as_sequence_Serializer, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Serializer, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Serializer, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_GC, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_9shibazuke_Serializer, /*tp_traverse*/
  __pyx_tp_clear_9shibazuke_Serializer, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_9shibazuke_Serializer, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_9shibazuke_10Serializer___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_9shibazuke_Serializer, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initshibazuke(void); /*proto*/
PyMODINIT_FUNC initshibazuke(void) {
  PyObject *__pyx_1 = 0;
  __pyx_init_filenames();
  __pyx_m = Py_InitModule4("shibazuke", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule("__builtin__");
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;};
  __pyx_vtabptr_9shibazuke_Serializer = &__pyx_vtable_9shibazuke_Serializer;
  *(void(**)(void))&__pyx_vtable_9shibazuke_Serializer._build_ref = (void(*)(void))__pyx_f_9shibazuke_10Serializer__build_ref;
  *(void(**)(void))&__pyx_vtable_9shibazuke_Serializer._handle_string = (void(*)(void))__pyx_f_9shibazuke_10Serializer__handle_string;
  *(void(**)(void))&__pyx_vtable_9shibazuke_Serializer._build = (void(*)(void))__pyx_f_9shibazuke_10Serializer__build;
  __pyx_type_9shibazuke_Serializer.tp_free = _PyObject_GC_Del;
  if (PyType_Ready(&__pyx_type_9shibazuke_Serializer) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_9shibazuke_Serializer.tp_dict, __pyx_vtabptr_9shibazuke_Serializer) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Serializer", (PyObject *)&__pyx_type_9shibazuke_Serializer) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; goto __pyx_L1;}
  __pyx_ptype_9shibazuke_Serializer = &__pyx_type_9shibazuke_Serializer;

  /* "c:\src\shibazuke\shibazuke.pyx":1 */
  __pyx_1 = __Pyx_Import(__pyx_n_struct, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_struct, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\shibazuke\shibazuke.pyx":1 */
  __pyx_1 = __Pyx_Import(__pyx_n_sys, 0); if (!__pyx_1) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_n_sys, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "c:\src\shibazuke\shibazuke.pyx":137 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("shibazuke");
}

static char *__pyx_filenames[] = {
  "shibazuke.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        obj->ob_type->tp_name, type->tp_name);
    return 0;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) type->ob_type;
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        if (!*t->p)
            return -1;
        if (t->i)
            PyString_InternInPlace(t->p);
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_tuple = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;
    
    py_srcfile = PyString_FromString(__pyx_filename);
    if (!py_srcfile) goto bad;
    py_funcname = PyString_FromString(funcname);
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    empty_tuple = PyTuple_New(0);
    if (!empty_tuple) goto bad;
    empty_string = PyString_FromString("");
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        empty_tuple,  /*PyObject *consts,*/
        empty_tuple,  /*PyObject *names,*/
        empty_tuple,  /*PyObject *varnames,*/
        empty_tuple,  /*PyObject *freevars,*/
        empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_tuple);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}
